function plotGates(gates)
%PLOTGATES plot gates in 3D
    for g = 1:length(gates)
        plotCircle3D(gates(g).position, ...
                     angle2rod(gates(g).orientation(1),...
                               gates(g).orientation(2),...
                               gates(g).orientation(3)), ...
                     gates(g).radius, 'r')
    end
end

